# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 16:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaNueva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('client', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=40)),
                ('surname', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[(3, 'Plata'), (4, 'Oro'), (5, 'Oro HD'), (10, 'Oro HD Plus'), (10, 'Platino'), (10, 'Nexus')], default=5, max_length=20)),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seguimientos.Venta')),
            ],
            options={
                'verbose_name_plural': 'ventas nuevas',
            },
        ),
    ]
