# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0003_auto_20170406_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='hd_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventanueva',
            name='mix_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventanueva',
            name='only_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventanueva',
            name='payment',
            field=models.CharField(choices=[(0, 'TC'), (1, 'Efectivo')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
