# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0004_auto_20170406_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanueva',
            name='hd_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1')], default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='mix_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='only_amount',
            field=models.IntegerField(choices=[(0, '0'), (1, '1'), (2, '2'), (3, '3'), (4, '4')], default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='payment',
            field=models.CharField(choices=[(0, 'TC'), (1, 'Efectivo')], default=0, max_length=10),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='service',
            field=models.CharField(choices=[(2, 'Prepago'), (3, 'Plata'), (4, 'Oro'), (5, 'Oro HD'), (10, 'Oro HD Plus'), (10, 'Platino'), (10, 'Nexus')], default=5, max_length=10),
        ),
    ]
