# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 15:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguimientos', '0005_auto_20170407_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='payment',
            field=models.IntegerField(choices=[(0, 'TC'), (1, 'Efectivo')], default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='service',
            field=models.IntegerField(choices=[(2, 'Prepago'), (3, 'Plata'), (4, 'Oro'), (5, 'Oro HD'), (10, 'Oro HD Plus'), (10, 'Platino'), (10, 'Nexus')], default=5),
        ),
    ]
