# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('seguimientos', '0006_auto_20170407_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
