# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 13:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0007_ventanueva_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='cash_amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventanueva',
            name='paid',
            field=models.NullBooleanField(),
        ),
        migrations.AddField(
            model_name='ventanueva',
            name='payoff',
            field=models.BooleanField(default=False),
        ),
    ]
