# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-10 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0008_auto_20170410_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ventanueva',
            name='cash_amount',
            field=models.IntegerField(),
        ),
    ]
