# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-11 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0009_auto_20170410_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='status',
            field=models.CharField(default='OK', max_length=10),
        ),
    ]
