# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-20 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0010_ventanueva_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='sds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='cash_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ventanueva',
            name='status',
            field=models.CharField(choices=[('Finalizada', 'Finalizada'), ('Venta Caída', 'Venta Caída'), ('Rechazada', 'Rechazada'), ('Prospect', 'Prospect'), ('Pendiente', 'Pendiente')], default='Finalizada', max_length=12),
        ),
    ]
