# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-26 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0011_auto_20170420_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='payoff_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
