# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-09 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimientos', '0012_ventanueva_payoff_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventanueva',
            name='reason',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
